app:
  prefix: "!"
  token: OTcyMDg2MjExNzkzNTI2ODE0.GlhThe.nHCbQoPVQWP_3a20rHLqNHucMWk9jllnYouTHk
  reg_chan_id: "1009139447402594304"
database:
  token: mongodb+srv://admin:eedin1234A%2F%2Fb@scrimbotdatabase.jfwoa.mongodb.net/scrimbot?retryWrites=true
riot:
  token: RGAPI-f5694d45-18a9-4d9a-8950-e065fdedd8d6
